package gui.msg;


public enum FrameAddOutputMsg implements GuiMsg {
	CASE_SENSITIVE, REGEX, STATIC, FINAL, ABSTRACT, ADD, REMOVE, CLEAR, UP, DOWN, CANCEL, OK, TITLE, ACCESS_MODIFIER, RETURN_TYPE, 
	METHOD_NAME, VOID, PARAMS, EXCEPTIONS, 
	PARAM_TYPE_LABEL, PARAM_NAME_LABEL, OUTPUT, TITLE_EDIT, PUBLIC, PRIVATE, PROTECTED, DEFAULT, PARAM_NAME, 
	IGNORE, WHITESPACES, LINE_BREAKS, TABS, EXTRA_SPACES, RECURSIVE, FIELD_TYPE, FIELD_NAME, FIELDS, 
	MSG_PARAMS,
	MSG_METHOD_NAME_MISSING, MSG_CLASS_NAME_MISSING, MSG_VALUE_MISSING, 
	MSG_FIELD_TYPE_MISSING, MSG_FIELD_NAME_MISSING, MSG_FIELD_ALREADY_DEFINED;
	
	public String prefix(){
		return "FrameAddOutput";
	}
	
	@Override
	public String toString() {
		return I18N.getVal(this);
	}
}
