package gui.msg;


public enum FrameTestMsg implements GuiMsg {
	ADD_BEHAVIOR,
	EDIT,
	CLOSE,
	EXTENSION,
	FILTER_MSG,
	OPEN,
	SAVE,
	NEW,
	FILE,
	ALUNO,
	NOTA,
	ERROS,
	RUN,
	CODE_TEACHER,
	DETAIL_RESULT,
	ADD_OUTPUT_TEST,
	ADD_STRUCT_TEST,
	PROJECT_NAME,
	STUDENT_DIR,
	BROWSE,
	STUDENT_DIRECTORY,
	REMOVE,
	CLEAR, 
	OPTIONS, CASE_SENSITIVE, REGEX, RECURSIVE, 
	FILE_NOT_FOUND, IO_EXCEPTION, FILE_TYPE, 
	OPEN_OPTIONS, FOLDER, JAR, ARCHIVE, JAVA, 
	MSG_PROJECT_NAME, MSG_STUDENT_FOLDER, MSG_FOLDER_NOT_EXISTS, FILETYPE_OPTIONS, SOURCE_FOLDER, TESTS;
	
	public String prefix(){
		return "FrameTest";
	}
}